# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Build iOS app"
  lane :app_build do
    scan(
      project: "TurboCalculator.xcodeproj",
      scheme: "TurboCalculator",
      destination: "platform=iOS Simulator,id=#{ENV['SIMULATOR_ID']}",
      app_identifier: "QAGuru.Calculator",
      derived_data_path: "./QAGuruDD",
      build_for_testing: true
    )
  end

  desc "Run tests at iOS app"
  lane :app_test do
    scan(
      derived_data_path: "./QAGuruDD",
      destination: "platform=iOS Simulator,id=#{ENV['SIMULATOR_ID']}",
      test_without_building: true,
      result_bundle: true,
      app_identifier: "QAGuru.Calculator",
      scheme: "TurboCalculator",
      reset_simulator: true,
      output_directory: "Report",
      output_types: "",
      reinstall_app: true,
      testplan: ENV['TEST_PLAN']
    )
  end

end
